version: "1.0"
info:
  model: int-scaffold
packages:
- name: TestProjectGitqProject
  gitServerName: SanthoshKUserSanthosh
  gitUrl: https://github.com/santhu736852
  gitUsername: santhu736852
  gitBranch: main
